parameters:
    ezplatform.fieldtype.matrix.identifier: 'ezmatrix'

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzSystems\EzPlatformMatrixFieldtype\FieldType\Type:
        autoconfigure: false
        autowire: true
        public: true
        parent: ezpublish.fieldType
        arguments:
            $fieldTypeIdentifier: '%ezplatform.fieldtype.matrix.identifier%'
        tags:
            - { name: ezplatform.field_type, alias: '%ezplatform.fieldtype.matrix.identifier%' }

    EzSystems\EzPlatformMatrixFieldtype\FieldType\Converter\MatrixConverter:
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: '%ezplatform.fieldtype.matrix.identifier%' }

    EzSystems\EzPlatformMatrixFieldtype\FieldType\Mapper\MatrixFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.definition, fieldType: '%ezplatform.fieldtype.matrix.identifier%' }
            - { name: ezplatform.field_type.form_mapper.value, fieldType: '%ezplatform.fieldtype.matrix.identifier%' }

    EzSystems\EzPlatformMatrixFieldtype\FieldType\Indexable:
        tags:
            - { name: ezplatform.field_type.indexable, alias: '%ezplatform.fieldtype.matrix.identifier%' }
